site_name: Documentação Dnit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    primary: "indigo"
nav:
  - Home: index.md
  - Historias de usuário: User Stories/userStories.md
  - Backlog: Backlog/backlog.md
  - Protótipo: Prototipo/prototipo.md
  - EAP: EAP/eap.md
  - Visão do Produto: visaodoproduto.md
  - Identidade visual: identidadeVisual/identidadeVisual.md
  - Historias de usuário: User Stories\userStories.md
  - Modelagem de Dados: modelagemDados/modelagemDeDados.md
  - Plano de Riscos: gestaoDoProjeto/planoDeRisco.md
  - Código de Conduta: codigoConduta/codConduta.md

  #- Backlog: Backlog\backlog.md
