site_name: Documentação Dnit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    primary: "indigo"
nav:
  - Home: index.md
  - Historias de usuário: User Stories/userStories.md
  - Backlog: Backlog/backlog.md
  - Protótipo: Prototipo/prototipo.md
  - EAP: EAP/eap.md
  - Comunicação: atasDeReuniao/atasReuniao.md
  - Visão do Produto: visaodoproduto.md
  - Custo e Risco:
    - Plano de Riscos: gestaoDoProjeto/planoDeRisco.md
    - Plano de Custos: gestaoDoProjeto/planoDeCusto.md
  - Identidade visual: identidadeVisual/identidadeVisual.md
  - Documento de arquitetura: projeto/arquitetura.md
  - Modelagem de Dados: modelagemDados/modelagemDeDados.md
  - Código de Conduta: codigoConduta/codConduta.md
  - Guia de Contribuicão: GuiaDeContribuicao/guiaDeContribuicao.md
  - Sprints:
    - Sprint 1: Sprints/Sprint_1.md
    - Sprint 2: Sprints/Sprint_2.md

  #- Backlog: Backlog\backlog.md
