site_name: Dumentação Dnit
theme:
  name: material
  features: navigation.tabs
  palette:
    primary: 'indigo'
nav:
    - 'Home': 'index.md'
    - 'Historias de usuário': 'User Stories\userStories.md'