site_name: Documentação Dnit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    primary: "indigo"
nav:
  - Home: index.md
  - Historias de usuário: User Stories/userStories.md
  - Backlog: Backlog/backlog.md
  - Protótipo: Prototipo/prototipo.md
  - EAP: EAP/eap.md
  - Visão do Produto: visaodoproduto.md
  - Custo e Risco:
    - Plano de Riscos: gestaoDoProjeto/planoDeRisco.md
    - Plano de Custos: gestaoDoProjeto/planoDeCusto.md
    - Gráfico de Gantt: gestaoDoProjeto/graficoGantt.md
  - Identidade visual: identidadeVisual/identidadeVisual.md
  - Código de Conduta: codigoConduta/codConduta.md
  - Estorias de usuario: GuiaDeContribuicao/guiaDeContribuicao.md

  #- Backlog: Backlog\backlog.md
