name: build_check

on:
  push:
      branches:
      - '**'
      - '!releases/**'
      - '!release/**'
      - '!main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: cd docs && mkdocs build -s