name: gh-deploy

on:
  pull_request:
    types:
    - closed
    branches:
    - main


jobs:

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: cd docs && mkdocs gh-deploy --verbose --strict --clean --force
